name: flutter_ferry_unions_issue
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  ferry: ^0.15.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.3.3
  ferry_generator: ^0.9.0-dev.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


dependency_overrides:
  ferry_generator:
    path: ../ferry/packages/ferry_generator
  gql_code_builder:
    path: ../gql/codegen/gql_code_builder
